-----------------------------------------------------------------------------------
--				Script to create tables in DSZ environement.
-----------------------------------------------------------------------------------

USE dsz_mfm_cms;

CREATE TABLE IF NOT EXISTS DSZ_CostCenter(
	IDCostCenter int,
	IDCustomer int,
	IDCustomerSegment int,
	CostCenterCode string,
	CostCenterDescription string,
	CostCenterVisible int,
	CostCenterSearchable int,
	IDUserCreated string,
	DateCreated string,
	IDUserUpdated string,
	Level int,
	IDParent int,
	Hierarchy string,
	ContactName string,
	Phone string,
	Email string,
	Notes string,
	DateUpdated string,
	SystemOfOrigin string,
	ForeignKey string,
	IsDelete int,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_Location(
	IDLocation int,
	IDCustomer int,
	IDCustomerSegment int,
	LocationDescription string,
	LocationVisible int,
	LocationSearch int,
	IDUserCreated string,
	DateCreated string,
	IDUserUpdated string,
	DateUpdated string,
	Level int,
	IDParent int,
	Hierarchy string,
	HierarchyString string,
	ExtendedDescription string,
	SystemOfOrigin string,
	ForeignKey string,
	InSiteFloor int,
	InSiteRoom int,
	InSiteFloorName string,
	InSiteBldgCode string,
	InSiteFloorCode string,
	InSiteBldgFriendlyName string,
	InSiteFloorFriendlyName string,
	ShowOnlineRequest int,
	SortOrder int,
	IDDrawing string,
	XCoord decimal(32,10),
	YCoord decimal(32,10),
	P1XCoord decimal(32,10),
	P1YCoord decimal(32,10),
	P2XCoord decimal(32,10),
	P2YCoord decimal(32,10),
	IDFloor int,
	IDCostCenter int,
	IDOccupancy int,
	IDUtilization int,
	SQFoot decimal(32,10),
	HCOID string,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_tblCostCenterContacts(
	IDCostCenterContact string,
	IDCustomer int,
	IDCustomerSegment int,
	IDCostCenter int,
	IDUser string,
	IDRound string,
	ContactName string,
	ContactPhone string,
	ContactEmail string,
	IsSafety int,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_tblRoundFindings(
	IDRoundFinding string,
	IDCustomer int,
	IDCustomerSegment int,
	IDRound string,
	IDRoundLibrary string,
	IDRoundLibraryItem string,
	IDRoundStatus int,
	IDLocation int,
	IDAsset string,
	Comments string,
	SurveyedCorrect int,
	SurveyedTotal int,
	IDWorkOrder string,
	IDUserCreated string,
	DateCreated string,
	ResolutionNotes string,
	IDCostCenter int,
	LocationOther string,
	ImageList string,
	NotApplicable int,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_tblRoundLibraries(
	IDRoundLibrary string,
	IDCustomer int,
	IDCustomerSegment int,
	LibraryName string,
	IDUserCreated string,
	DateCreated string,
	IDUserUpdated string,
	DateUpdated string,
	Deleted int,
	IDIcon string,
	DisplayOrder int,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_tblRoundLibraryItems(
	IDRoundLibraryItem string,
	IDCustomer int,
	IDCustomerSegment int,
	IDRoundLibrary string,
	IDCMSCategory int,
	LibraryItem string,
	IDCodeLibrary string,
	Notes string,
	DisplayOrder int,
	IDCostCenterResponsible int,
	CreateWorkOrder int,
	WODescription string,
	IDWOPriority int,
	IDWOCategory int,
	IDWOTrade int,
	IDWOStatus int,
	WODateAvailable string,
	WODateNeededBy string,
	IDUserCreated string,
	DateCreated string,
	IDUserUpdated string,
	DateUpdated string,
	Deleted int,
	ResolutionNotes string,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_tblRounds(
	IDRound string,
	IDCustomer int,
	IDCustomerSegment int,
	IDRoundTemplate string,
	IDLocation int,
	IDCostCenter int,
	IDUserCreated string,
	DateCreated string,
	IDRoundStatus int,
	Deleted int,
	DateFinalized string,
	IDRoundSchedule string,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_tblRoundTeams(
	IDRoundTeam string,
	IDCustomer int,
	IDCustomerSegment int,
	IDRound string,
	IDUser string,
	IDUserCreated string,
	DateCreated string,
	ContactName string,
	ContactPhone string,
	ContactEmail string,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_tblRoundTemplates(
	IDRoundTemplate string,
	IDCustomer int,
	IDCustomerSegment int,
	RoundName string,
	Note string,
	IDUserCreated string,
	DateCreated string,
	IDUserUpdated string,
	DateUpdated string,
	Deleted int,
	IDCategory int,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_WorkOrder(
	IDWorkOrder string,
	IDCustomer int,
	IDCustomerSegment int,
	WONumber int,
	WODescription string,
	WORequestComments string,
	WORequestorName string,
	WORequestorPhone string,
	WORequestorEmail string,
	IDWOCostCenter int,
	IDWOPriority int,
	IDWOCategory int,
	IDWOTrade int,
	IDWOLocation int,
	LocationOther string,
	IDWOStatus int,
	WODateAvailable string,
	WODateNeededBy string,
	WODateCompleted string,
	WOCompletionComments string,
	IDPassFail int,
	IDUserCreated string,
	DateCreated string,
	IDUserUpdated string,
	DateUpdated string,
	SendToPrinter int,
	SendEmail int,
	IDParentWO string,
	AssignmentHierarchy string,
	AssetCount int,
	Archived int,
	IDContract string,
	IDProblem int,
	SystemOfOrigin string,
	ForeignKey string,
	XCoord decimal(32,10),
	YCoord decimal(32,10),
	EmailLevel1 string,
	EmailLevel2 string,
	IDWOBillableStatus int,
	ScheduledDate string,
	EstimatedHours decimal(32,10),
	P1XCoord decimal(32,10),
	P1YCoord decimal(32,10),
	P2XCoord decimal(32,10),
	P2YCoord decimal(32,10),
	IsDelete int,
	IDProject string,
	IDUserCompleted string,
	ProcessID string,
	IDRequester string,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_CustomerSegment(
	IDCustomerSegment int,
	IDCustomer int,
	SegmentNumber int,
	SegmentName string,
	SegmentAddress1 string,
	SegmentAddress2 string,
	SegmentAddress3 string,
	SegmentCity string,
	IDSegmentCountry int,
	IDSegmentRegion int,
	SegmentPostalCode string,
	IDSegmentTimeZone int,
	IDSegmentStatus int,
	SegmentShared int,
	SegmentNotes string,
	IDUserCreated string,
	DateCreated string,
	IDUserUpdated string,
	DateUpdated string,
	medTesterEnabled int,
	Logo binary,
	AssignmentUseDefaultEmail int,
	AssignmentDefaultEmail string,
	AssignmentEmailSubject string,
	AssignmentEmailBody string,
	AssignmentPageBody string,
	UseRequesterTable int,
	Theme string,
	TC_ShowStartTime int,
	TC_ShowEndTime int,
	RequisitionUserEnteredRequisitionID int,
	CMSInSiteEnabled int,
	CMSInSiteResource string,
	WOAutoFillCompleteDate int,
	RequiredFieldColor string,
	MoveDays int,
	MoveMonday int,
	MoveTuesday int,
	MoveWednesday int,
	MoveThursday int,
	MoveFriday int,
	MoveSaturday int,
	MoveSunday int,
	MoveStatus int,
	MoveMessage string,
	WOFutureClose int,
	ReqAssetNote int,
	UserAvailability int,
	MaxTimeCharge float,
	RenewalDays int,
	IDCustomerSegment2 string,
	IDCustomer2 string,
	WOAllowCompleteDate int,
	SharedWONumbering int,
	RequisitionDisableIssueTo int,
	RequisitionDefaultIssueTo int,
	RequisitionDisableWONumber int,
	RequisitionShowForeignKey int,
	RequisitionHideTaxRate int,
	RequisitionHideCategory int,
	RequisitionHideVendorAddress int,
	RequisitionDefaultMaterialType int,
	RequisitionHideOrderUOM int,
	RequisitionDefaultOrderUOM int,
	RequisitionHideOrderUOMFactor int,
	RequisitionDefaultOrderUOMFactor decimal(32,10),
	RequisitionDisableVendorPartNumberAutopopulate int,
	MaterialDisableNegativeReceipts int,
	MaterialDisableReceiptQuantityGreaterThanOrdered int,
	UseLocationLookup int,
	RequisitionMaxDescriptionCharacters int,
	RequisitionQuantityPositiveInteger int,
	RequisitionDisableMaterialType int,
	RequisitionDisableVendorUnitCost int,
	RequisitionUnitCostPositive int,
	SupportLinkText string,
	WOReceiveAllToComplete int,
	AutoLoginEnabled int,
	WOAssetOverride int,
	CMSTechEnableWOSignatures int,
	IDSegmentCategory int,
	CMSTechEnableAutomaticTCCalculation int,
	CMSTechEnableAssetCategoryStandardDescriptions int,
	CMSTechShowMaterialChargeOnWOCompleteTab int,
	HeaderBarColor40 string,
	HeaderBarFontColor40 string,
	PopulateCostCenterOnLocationSelection int,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

CREATE TABLE IF NOT EXISTS DSZ_Status(
	IDStatus int,
	IDCustomer int,
	IDCustomerSegment int,
	IDCMSModule int,
	IDCMSStatus int,
	StatusDescription string,
	StatusVisible int,
	StatusSearchable int,
	Level int,
	IDParent int,
	IDUserCreated string,
	DateCreated string,
	IDUserUpdated string,
	DateUpdated string,
	Hierarchy string,
	AllowEdits int,
	HierarchyString string,
	ForeignKey string,
	dsz_process_id string COMMENT 'System column that stores the unique identifier for the process or job used to create the record',
	dsz_insert_dt string COMMENT 'System column that stores the date on which the record was inserted in the table')
STORED AS AVRO TBLPROPERTIES ('avro.output.codec'='snappy');

